# Generated by Django 4.2.8 on 2023-12-10 22:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('AdmissionID', models.IntegerField(primary_key=True, serialize=False)),
                ('AdmissionDate', models.DateField()),
                ('Expected_DischargeDate', models.DateField()),
                ('Reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Required_Specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.IntegerField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
                ('Availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StayDetails',
            fields=[
                ('StayDetailsID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('AdmissionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.admission')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('TreatmentID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProcedureDescription', models.TextField()),
                ('AppointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_TestResults',
            fields=[
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('TestResults', models.CharField(max_length=100)),
                ('TreatmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_Medications',
            fields=[
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('Medications', models.CharField(max_length=100)),
                ('TreatmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='StayDetails_Meals',
            fields=[
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('Meals', models.CharField(max_length=100)),
                ('StayDetailsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.staydetails')),
            ],
        ),
        migrations.CreateModel(
            name='StayDetails_ConditionUpdates',
            fields=[
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('ConditionUpdates', models.CharField(max_length=255)),
                ('StayDetailsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.staydetails')),
            ],
        ),
        migrations.CreateModel(
            name='StayDetails_AdministeredTreatments',
            fields=[
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('AdministeredTreatments', models.CharField(max_length=255)),
                ('StayDetailsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.staydetails')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_ContactDetails',
            fields=[
                ('ContactDetails', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_ContactDetails',
            fields=[
                ('ContactDetails', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DoctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('DischargeID', models.IntegerField(primary_key=True, serialize=False)),
                ('DischargeDate', models.DateField()),
                ('Reason', models.CharField(max_length=255)),
                ('AdmissionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.admission')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='DoctorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='PatientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient'),
        ),
        migrations.AddField(
            model_name='admission',
            name='PatientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient'),
        ),
        migrations.AddField(
            model_name='admission',
            name='RoomNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room'),
        ),
    ]
