# Generated by Django 4.2.8 on 2023-12-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Room_Type',
            field=models.CharField(max_length=20),
        ),
    ]
