# Generated by Django 4.2.8 on 2023-12-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='End_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
