# Generated by Django 4.2.8 on 2023-12-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_admission_admissionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
