# Generated by Django 4.2.8 on 2023-12-20 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_admission_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Start_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
