# Generated by Django 4.2.8 on 2023-12-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_admission_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Status',
            field=models.CharField(max_length=10),
        ),
    ]
