# Generated by Django 4.2.8 on 2023-12-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='Expected_DischargeDate',
        ),
        migrations.AlterField(
            model_name='admission',
            name='AdmissionDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='Reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discharge',
            name='DischargeDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staydetails',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staydetails_administeredtreatments',
            name='dateadded',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staydetails_conditionupdates',
            name='dateadded',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staydetails_meals',
            name='dateadded',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treatment_medications',
            name='dateadded',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treatment_testresults',
            name='dateadded',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
