# Generated by Django 4.2.8 on 2023-12-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentadnission',
            name='Treatment_Details',
            field=models.TextField(max_length=255),
        ),
    ]
