# Generated by Django 4.2.8 on 2023-12-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_treatmentadnission_treatment_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TreatmentAdnission',
            new_name='TreatmentAdmission',
        ),
    ]
