# Generated by Django 4.2.8 on 2023-12-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_treatmentadnission_treatmentadmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentadmission',
            name='price',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
    ]
