# Generated by Django 4.2.8 on 2023-12-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_treatmentadmission_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Reason',
            field=models.CharField(default='Reason', max_length=255),
        ),
    ]
