# Generated by Django 4.2.8 on 2023-12-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_bill_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Role',
            field=models.CharField(max_length=255),
        ),
    ]
